import logging
import os
import re
import time

import altair
import geopandas
import numpy
import pandas
from pint import Unit
import pygeoprocessing

from natcap.invest import __version__
from natcap.invest import gettext
from natcap.invest.reports import jinja_env
from natcap.invest.reports import vector_utils
from natcap.invest.reports import raster_utils
from natcap.invest.spec import ModelSpec
from natcap.invest.unit_registry import u

LOGGER = logging.getLogger(__name__)

TEMPLATE = jinja_env.get_template('models/recreation.html')


def plot_visitation_map(geodataframe, variable):
    min_val = geodataframe[variable][geodataframe[variable] > 0].min()
    chart = altair.Chart(geodataframe).mark_geoshape(
        stroke="gray",
        strokeWidth=0.5,
    ).project(
        type='identity',
        reflectY=True
    ).encode(
        fill=altair.condition(
            altair.datum[variable] > 0,
            altair.Fill(
                variable,
                type='quantitative',
                scale=altair.Scale(
                    scheme='viridis',
                    type='log',
                    domainMin=min_val,  # must exclude 0s if using log
                )
            ),
            altair.value('white')
        ),
    )
    return chart


def report(file_registry: dict, args_dict: dict, model_spec: ModelSpec,
           target_html_filepath: str):
    """Generate an HTML summary of model results.

    Args:
        file_registry (dict): The ``natcap.invest.FileRegistry.registry``
            that was returned by the model's ``execute`` method.
        args_dict (dict): The arguments that were passed to the model's
            ``execute`` method.
        model_spec (natcap.invest.spec.ModelSpec): the model's ``MODEL_SPEC``.
        target_html_filepath (str): path to an HTML file to be generated by
            this function.

    Returns:
        ``None``
    """
    # Plot PUD, TUD, and combined results as choropleths.
    vis_charts = []
    regression_data = geopandas.read_file(file_registry['regression_data'])
    visitation_variables = ['pr_PUD', 'pr_TUD', 'avg_pr_UD']
    if 'scenario_results' in file_registry:
        # Join tables so that all vegalite specifications can share the dataset
        scenario_data = geopandas.read_file(file_registry['scenario_results'])
        regression_data['pr_UD_EST'] = scenario_data['pr_UD_EST']
        visitation_variables.append('pr_UD_EST')
    for var in visitation_variables:
        chart = plot_visitation_map(regression_data, var)
        vis_charts.append(chart)

    # Give user options for transformations and display?
    # Plotting points instead of polygons is significantly cheaper, 1 vertex instead
    # of 5 or 7, and all the 0s could be omitted, maybe.

    xmin, ymin, xmax, ymax = regression_data.total_bounds
    xy_ratio = (xmax - xmin) / (ymax - ymin)
    if raster_utils._extra_wide_aoi(xy_ratio):
        vis_maps_chart = altair.vconcat(*vis_charts)
    else:
        if len(vis_charts) == 4:
            vis_maps_chart = altair.vconcat(
                altair.hconcat(*vis_charts[:2]).resolve_scale(
                    fill='independent'
                ),
                altair.hconcat(*vis_charts[2:]).resolve_scale(
                    fill='independent'
                )
            )
        elif raster_utils._wide_aoi(xy_ratio):
            vis_maps_chart = altair.vconcat(*vis_charts)
        else:
            vis_maps_chart = altair.hconcat(*vis_charts)

    vis_maps_chart = vis_maps_chart.resolve_scale(
        fill='independent'
    )
    vis_maps_dict = vis_maps_chart.to_dict()
    regression_data_name = list(vis_maps_dict['datasets'])[0]
    regression_data_json = json.dumps(vis_maps_dict['datasets'][regression_data_name])
    vis_maps_dict['datasets'][regression_data_name] = []
    vis_maps_json = json.dumps(vis_maps_dict)

    # vis_maps_json = vis_maps_chart.to_json()

    vistation_maps_caption = 'a caption'

    # Plot annual and monthly results? Not neccessary at first

    if 'regression_coefficients' in file_registry:
        estimates_df = pandas.read_csv(
            file_registry['regression_coefficients'])

        # Display table of regression coefficients & regression_summary.txt stats
        estimates_df = estimates_df.sort_values('predictor')
        effect_size_table = estimates_df.to_html(index=False)
        patterns = r'Residual standard error|Multiple R-squared|Adjusted R-squared|SSres'
        with open(file_registry['regression_summary']) as summary_file:
            summary_lines = ''
            for line in summary_file.readlines():
                if re.findall(patterns, line):
                    summary_lines += line
        regression_summary_html = f'<pre>{summary_lines}</pre>'

        # Plot effect sizes of predictors
        def plot_effect_sizes(dataframe):
            # drop the intercept predictor row
            dataframe = dataframe[dataframe['predictor'] != '(Intercept)'].copy()
            dataframe['lower_stderr'] = dataframe['estimate'] - dataframe['stderr']
            dataframe['upper_stderr'] = dataframe['estimate'] + dataframe['stderr']
            max_abs_value = max(dataframe['lower_stderr'].abs().max(), dataframe['upper_stderr'].abs().max())
            base = altair.Chart(dataframe)
            effect_size = base.mark_point(
                color='red',
                size=100
            ).encode(
                x=altair.X(
                    'estimate:Q',
                    scale=altair.Scale(
                        domain=[-max_abs_value, max_abs_value],
                        domainMid=0),
                    title='Effect size (coefficient estimate)'),
                y=altair.Y('predictor:N', title='Predictor variable')
            )
            effect_stderr = base.mark_rule().encode(
                x='lower_stderr:Q',
                x2='upper_stderr:Q',
                y=altair.Y('predictor:N')
            )
            effect_size_chart = effect_stderr + effect_size
            effect_size_chart = effect_size_chart.properties(
                width=400,
                height=400
            ).configure_axis(**vector_utils.AXIS_CONFIG)
            return effect_size_chart

        effect_size_chart = plot_effect_sizes(estimates_df)
        effect_size_chart_json = effect_size_chart.to_json()

        # Plot maps of aggregated predictors
        predictor_variables = estimates_df['predictor']
        predictor_variables = predictor_variables[predictor_variables != '(Intercept)']
        predictor_maps = []
        for variable in predictor_variables:
            chart = altair.Chart(regression_data).mark_geoshape(
                stroke="gray",
                strokeWidth=0.5,
            ).project(
                type='identity',
                reflectY=True
            ).encode(
                fill=altair.condition(
                    altair.datum[variable] > 0,
                    altair.Fill(
                        variable,
                        type='quantitative',
                        scale=altair.Scale(
                            scheme='viridis',
                            # type='log',
                            # domainMin=min_val,  # must exclude 0s if using log
                        )
                    ),
                    altair.value('white')
                ),
            )
            predictor_maps.append(chart)

        n_rows, n_cols = raster_utils._choose_n_rows_n_cols(
            xy_ratio, len(predictor_maps), small_plots=False)

        predictor_maps_chart = altair.vconcat(
            *[altair.hconcat(
                *predictor_maps[x:x + n_cols]).resolve_scale(fill='independent')
              for x in range(0, len(predictor_maps), n_cols)]
        ).resolve_scale(
            fill='independent'
        )

        predictor_maps_dict = predictor_maps_chart.to_dict()
        predictor_maps_dict['datasets'][regression_data_name] = []
        predictor_maps_json = json.dumps(predictor_maps_dict)
        predictor_maps_caption = 'a caption'

        # Plot distributions of predictor and response variables

        # Scatterplot correllations between all variables
        variables = predictor_variables.to_list()
        variables.append('avg_pr_UD')
        correlation_plot = altair.Chart(regression_data).mark_circle().encode(
            altair.X(altair.repeat("column"), type='quantitative'),
            altair.Y(altair.repeat("row"), type='quantitative')
        ).properties(
            width=150,
            height=150
        ).repeat(
            row=variables,
            column=list(reversed(variables))
        )
        correlation_plot_dict = correlation_plot.to_dict()
        correlation_plot_dict['datasets'][regression_data_name] = []
        correlation_plot_json = json.dumps(correlation_plot_dict)

    with open(target_html_filepath, 'w', encoding='utf-8') as target_file:
        target_file.write(TEMPLATE.render(
            report_script=model_spec.reporter,
            invest_version=__version__,
            report_filepath=target_html_filepath,
            model_id=model_spec.model_id,
            model_name=model_spec.model_title,
            model_description=model_spec.about,
            userguide_page=model_spec.userguide,
            timestamp=time.strftime('%Y-%m-%d %H:%M'),
            args_dict=args_dict,
            model_spec_outputs=model_spec.outputs,
            vis_maps_json=vis_maps_json,
            visitation_maps_caption=vistation_maps_caption,
            predictor_maps_json=predictor_maps_json,
            predictor_maps_caption=predictor_maps_caption,
            regression_data_name=regression_data_name,
            regression_data_json=regression_data_json,
            effect_size_chart_json=effect_size_chart_json,
            effect_size_table=effect_size_table,
            regression_summary_html=regression_summary_html,
            correlation_plot_json=correlation_plot_json
        ))

    LOGGER.info(f'Created {target_html_filepath}')


if __name__ == '__main__':
        
    import json

    from natcap.invest.recreation import MODEL_SPEC
    from natcap.invest import datastack

    file_registry_path = 'C:/Users/dmf/projects/forum/rec/sampledata_319/file_registry.json'
    param_set = datastack.extract_parameters_from_logfile(
        'C:/Users/dmf/projects/forum/rec/sampledata_319/InVEST-recreation-log-2026-04-15--16_54_59.txt')

    with open(file_registry_path) as registry_file:
        file_registry = json.load(registry_file)

    report(file_registry, param_set.args, MODEL_SPEC, 'recreation_report.html')
