import logging
import os
import time

import altair
import geopandas
import numpy
import pandas
from pint import Unit
import pygeoprocessing

from natcap.invest import __version__
from natcap.invest import gettext
from natcap.invest.reports import jinja_env, raster_utils, report_constants
from natcap.invest.reports.raster_utils import RasterDatatype, RasterPlotConfig
from natcap.invest.spec import ModelSpec
from natcap.invest.unit_registry import u

LOGGER = logging.getLogger(__name__)

TEMPLATE = jinja_env.get_template('models/recreation.html')


def report(file_registry: dict, args_dict: dict, model_spec: ModelSpec,
           target_html_filepath: str):
    """Generate an HTML summary of model results.

    Args:
        file_registry (dict): The ``natcap.invest.FileRegistry.registry``
            that was returned by the model's ``execute`` method.
        args_dict (dict): The arguments that were passed to the model's
            ``execute`` method.
        model_spec (natcap.invest.spec.ModelSpec): the model's ``MODEL_SPEC``.
        target_html_filepath (str): path to an HTML file to be generated by
            this function.

    Returns:
        ``None``
    """
    # Plot PUD, TUD, and combined results as choropleths.
    regression_data = geopandas.read_file(file_registry['regression_data'])

    vis_charts = []
    for var in ['pr_PUD', 'pr_TUD', 'avg_pr_UD']:
        min_val = regression_data[var][regression_data[var] > 0].min()
        chart = altair.Chart(regression_data).mark_geoshape(
            stroke="gray",
            strokeWidth=0.5,
        ).project(
            type='identity',
            reflectY=True
        ).encode(
            fill=altair.condition(
                altair.datum[var] > 0,
                altair.Fill(
                    var,
                    type='quantitative',
                    scale=altair.Scale(
                        scheme='viridis',
                        type='log',
                        domainMin=min_val,  # must exclude 0s if using log
                    )
                ),
                altair.value('white')
            ),
        )
        vis_charts.append(chart)

    # TODO: check aspect ratio and choose hconcat vs vconcat
    vis_map_json = altair.hconcat(
        *vis_charts).resolve_scale(fill='independent').to_json()

    vistation_maps_caption = 'a caption'

    # Give user options for transformations and display?
    # Plotting points instead of polygons is significantly cheaper, 1 vertex instead
    # of 5 or 7, and all the 0s could be omitted, maybe.  

    if file_registry['scenario_results']:
        # Plot side-by-side baseline and scenario visitation maps
        # This either relies on the new fitted baseline values from
        # https://github.com/natcap/invest/issues/2148
        # or duplicates a map from above
        pass

    # Plot annual and monthly results? Not neccessary at first

    if file_registry['regression_coefficients']:
        # Display table of regression coefficients & regression_summary.txt stats

        # Plot effect sizes of predictors

        # Plot maps of aggregated predictors

        # Plot distributions of predictor and response variables

        # Scatterplot correllations between all variables
        pass

    with open(target_html_filepath, 'w', encoding='utf-8') as target_file:
        target_file.write(TEMPLATE.render(
            report_script=model_spec.reporter,
            invest_version=__version__,
            report_filepath=target_html_filepath,
            model_id=model_spec.model_id,
            model_name=model_spec.model_title,
            model_description=model_spec.about,
            userguide_page=model_spec.userguide,
            timestamp=time.strftime('%Y-%m-%d %H:%M'),
            args_dict=args_dict,
            model_spec_outputs=model_spec.outputs,
            vis_map_json=vis_map_json,
            visitation_maps_caption=vistation_maps_caption,
        ))

    LOGGER.info(f'Created {target_html_filepath}')


if __name__ == '__main__':
        
    import json

    from natcap.invest.recreation import MODEL_SPEC
    from natcap.invest import datastack

    file_registry_path = 'C:/Users/dmf/projects/forum/rec/sampledata_319/file_registry.json'
    param_set = datastack.extract_parameters_from_logfile(
        'C:/Users/dmf/projects/forum/rec/sampledata_319/InVEST-recreation-log-2026-04-15--16_54_59.txt')

    with open(file_registry_path) as registry_file:
        file_registry = json.load(registry_file)

    report(file_registry, param_set.args, MODEL_SPEC, 'recreation_report.html')
