import logging
import os
import time

import numpy
import pandas
from pint import Unit
import pygeoprocessing

from natcap.invest import gettext
from natcap.invest.reports import jinja_env, raster_utils, report_constants
from natcap.invest.spec import ModelSpec
from natcap.invest.unit_registry import u

LOGGER = logging.getLogger(__name__)

TEMPLATE = jinja_env.get_template('models/carbon.html')


def report(file_registry: dict, args_dict: dict, model_spec: ModelSpec,
           target_html_filepath: str):
    """Generate an HTML summary of model results.

    Args:
        file_registry (dict): The ``natcap.invest.FileRegistry.registry``
            that was returned by the model's ``execute`` method.
        args_dict (dict): The arguments that were passed to the model's
            ``execute`` method.
        model_spec (natcap.invest.spec.ModelSpec): the model's ``MODEL_SPEC``.
        target_html_filepath (str): path to an HTML file to be generated by
            this function.

    Returns:
        ``None``
    """

    aet_config = raster_utils.RasterPlotConfig(file_registry['aet'], 'continuous')
    fractp_config = raster_utils.RasterPlotConfig(file_registry['fractp'], 'continuous')
    wyield_config = raster_utils.RasterPlotConfig(file_registry['wyield'], 'continuous')

    raster_list = [aet_config, fractp_config, wyield_config]
    img_src = raster_utils.plot_and_base64_encode_rasters(raster_list)
    outputs_caption = []

    with open(target_html_filepath, 'w', encoding='utf-8') as target_file:
        target_file.write(TEMPLATE.render(
            report_script=__file__,
            model_id=model_spec.model_id,
            model_name=model_spec.model_title,
            model_description='about the model',
            userguide_page=model_spec.userguide,
            timestamp=time.strftime('%Y-%m-%d %H:%M'),
            args_dict=args_dict,
            stats_table_note=report_constants.STATS_TABLE_NOTE,
            model_spec_outputs=model_spec.outputs,
            primary_raster_outputs=img_src
        ))

    LOGGER.info(f'Created {target_html_filepath}')
