name: Nightly InVEST Builds

on: [push]

jobs:
  build-and-test-workflow:
    uses: ./.github/workflows/build-and-test.yml

  invest-autotest:
    needs: build-and-test-workflow
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    steps:
      - name: invest-autotest
        run: make invest_autotest
