name: Nightly InVEST Builds

on: [push]

jobs:
  run-autotest:
    steps:
      - name: call build-and-test workflow
        uses: ./.github/workflows/build-and-test.yml

      - name: invest-autotest
        run: make invest_autotest

